export const SEND_MULTINOTIFICATIONS_REQUEST = 'SEND_MULTINOTIFICATIONS_REQUEST';
export const SEND_MULTINOTIFICATIONS_SUCCESS = 'SEND_MULTINOTIFICATIONS_SUCCESS';
export const SEND_MULTINOTIFICATIONS_FAILED = 'SEND_MULTINOTIFICATIONS_FAILED';
export const SEND_MULTINOTIFICATIONS_RESET = 'SEND_MULTINOTIFICATIONS_RESET';

export const SEND_NOTIFICATION_REQUEST = 'SEND_NOTIFICATION_REQUEST';
export const SEND_NOTIFICATION_SUCCESS = 'SEND_NOTIFICATION_SUCCESS';
export const SEND_NOTIFICATION_FAILED = 'SEND_NOTIFICATION_FAILED';
export const SEND_NOTIFICATION_RESET = 'SEND_NOTIFICATION_RESET';

export const SHOW_NOTIFICATION_REQUEST = 'SHOW_NOTIFICATION_REQUEST';
export const SHOW_NOTIFICATION_SUCCESS = 'SHOW_NOTIFICATION_SUCCESS';
export const SHOW_NOTIFICATION_FAILED = 'SHOW_NOTIFICATION_FAILED';
export const SHOW_NOTIFICATION_RESET = 'SHOW_NOTIFICATION_RESET';

export const SEEN_NOTIFICATION_REQUEST = 'SEEN_NOTIFICATION_REQUEST';
export const SEEN_NOTIFICATION_SUCCESS = 'SEEN_NOTIFICATION_SUCCESS';
export const SEEN_NOTIFICATION_FAILED = 'SEEN_NOTIFICATION_FAILED';
export const SEEN_NOTIFICATION_RESET = 'SEEN_NOTIFICATION_RESET';
