stages:
  - build
before_script:
  - export PRODUCT_VERSION=$(date '+%y-%m-%d-%H-%M')
createImage:
  stage: build
  script:
    - echo $PRODUCT_VERSION
    - export IMAGE_TAG=45.82.137.66:5000/psya_redesign:$PRODUCT_VERSION
    - docker login -u rayaregistry -p ok2711letsgo http://45.82.137.66:5000
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - develop
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
