export const MHESAM_ISSUEREQUEST_REQUEST = 'MHESAM_ISSUEREQUEST_REQUEST';
export const MHESAM_ISSUEREQUEST_SUCCESS = 'MHESAM_ISSUEREQUEST_SUCCESS';
export const MHESAM_ISSUEREQUEST_FAILED = 'MHESAM_ISSUEREQUEST_FAILED';
export const MHESAM_ISSUEREQUEST_RESET = 'MHESAM_ISSUEREQUEST_RESET';

export const MHESAM_USERCREDITLIST_REQUEST = 'MHESAM_USERCREDITLIST_REQUEST';
export const MHESAM_USERCREDITLIST_SUCCESS = 'MHESAM_USERCREDITLIST_SUCCESS';
export const MHESAM_USERCREDITLIST_FAILED = 'MHESAM_USERCREDITLIST_FAILED';
export const MHESAM_USERCREDITLIST_RESET = 'MHESAM_USERCREDITLIST_RESET';

export const MHESAM_PURCHASEUPDATE_REQUEST = 'MHESAM_PURCHASEUPDATE_REQUEST';
export const MHESAM_PURCHASEUPDATE_SUCCESS = 'MHESAM_PURCHASEUPDATE_SUCCESS';
export const MHESAM_PURCHASEUPDATE_FAILED = 'MHESAM_PURCHASEUPDATE_FAILED';
export const MHESAM_PURCHASEUPDATE_RESET = 'MHESAM_PURCHASEUPDATE_RESET';

export const MHESAM_OTPSEND_REQUEST = 'MHESAM_OTPSEND_REQUEST';
export const MHESAM_OTPSEND_SUCCESS = 'MHESAM_OTPSEND_SUCCESS';
export const MHESAM_OTPSEND_FAILED = 'MHESAM_OTPSEND_FAILED';
export const MHESAM_OTPSEND_RESET = 'MHESAM_OTPSEND_RESET';
